trigger: none
pr: none

pool:
  name: SelfHosted

steps:
- task: PowerShell@2
  displayName: Test embedded Docker
  inputs:
    targetType: inline
    pwsh: true
    script: |
      Write-Host "Testing PowerShell"
      pwsh --version

      Write-Host "Testing Docker"
      docker --version
      docker info

      Write-Host "Running hello-world"
      docker run --rm hello-world